#!/usr/bin/env python3
"""Generate the Runtime C ABI and native C++ module glue from one YAML schema."""

import argparse
import sys
from pathlib import Path


GENERATED = "// Generated by script/generate_runtime_api.py. Do not edit."

HELP = """
configuration:
  The default schema is conf/runtime_api.yaml. It uses two-space indentation and
  mapping entries only; tabs, sequences, anchors, aliases, and multiline scalars
  are not supported.

  Required top-level keys:
    abi_version             Integer ABI version written to FYUU_ABI_VERSION.
    module                  C++ module name.
    namespace               Namespace exported by the native module.
    results                 Result mappings.
    runtime_states          Runtime state mappings.
    log_levels              Log level mappings.
    platform_callbacks      Platform C field and C++ method mappings.
    application_callbacks   Application C field and C++ method mappings.

  Result and state entry:
    CppName:
      c_name: FYUU_C_ENUM_NAME
      value: 0

  Callback entry:
    callback_key:
      c_name: descriptor_field_name
      cpp_name: NativeMethodName  # only when the C++ glue forwards this callback

generated files:
  include/fyuu_types.h
  include/fyuu_result.h
  include/fyuu_platform.h
  include/fyuu_log.h
  include/fyuu_runtime.h
  runtime/module/generated/api_types.cppm
  runtime/module/internal/generated/api_glue.cpp

examples:
  python script/generate_runtime_api.py
  python script/generate_runtime_api.py --check
  python script/generate_runtime_api.py --schema conf/runtime_api.yaml

exit status:
  0  Files generated successfully, or --check found no differences.
  1  --check found stale generated files.
  2  The schema could not be read or validated.
"""


def parse_scalar(value):
	if value.isdecimal():
		return int(value)
	if value == "true":
		return True
	if value == "false":
		return False
	return value


def load_yaml(path):
	root = {}
	stack = [(-1, root)]
	for line_number, original in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
		if not original.strip() or original.lstrip().startswith("#"):
			continue
		indent = len(original) - len(original.lstrip(" "))
		if "\t" in original[:indent] or indent % 2:
			raise ValueError(f"{path}:{line_number}: indentation must use pairs of spaces")
		line = original.strip()
		if ":" not in line:
			raise ValueError(f"{path}:{line_number}: expected a mapping entry")
		key, value = line.split(":", 1)
		key = key.strip()
		value = value.strip()
		while stack[-1][0] >= indent:
			stack.pop()
		parent = stack[-1][1]
		if key in parent:
			raise ValueError(f"{path}:{line_number}: duplicate key {key}")
		if value:
			parent[key] = parse_scalar(value)
		else:
			parent[key] = {}
			stack.append((indent, parent[key]))
	return root


def require_keys(mapping, keys, context):
	missing = [key for key in keys if key not in mapping]
	if missing:
		raise ValueError(f"{context}: missing {', '.join(missing)}")


def render_types(schema):
	return f"""{GENERATED}
#pragma once

#include <stdbool.h>
#include <stdint.h>

/* Version carried by every extensible descriptor passed across the C ABI. */
#define FYUU_ABI_VERSION ((uint32_t){schema['abi_version']}u)
"""


def render_result(schema):
	items = ",\n".join(
		f"\t{item['c_name']} = {item['value']}"
		for item in schema["results"].values()
	)
	return f"""{GENERATED}
#pragma once

#include "fyuu_types.h"

/* Stable result codes returned by the C ABI and mapped by fyuu_engine::Result. */
typedef enum Fyuu_Result {{
{items}
}} Fyuu_Result;
"""


def render_platform(schema):
	callbacks = schema["platform_callbacks"]
	require_keys(callbacks, ("initialize", "pump_events", "shutdown"), "platform_callbacks")
	return f"""{GENERATED}
#pragma once

#include <stddef.h>
#include <stdint.h>

#include "api_macro.h"
#include "fyuu_result.h"

#if defined(__cplusplus)
extern "C" {{
#endif

/*
 * Native call chain:
 * fyuu_engine::Platform -> C ABI entry -> platform state -> callback -> generated thunk -> Platform.
 * C callers enter at the C ABI entry and provide callbacks directly.
 */
typedef struct Fyuu_Platform Fyuu_Platform;

/* Called by Fyuu_RuntimeInitialize before the application initialize callback. */
typedef Fyuu_Result (LIB_CALL* Fyuu_PlatformInitializeCallback)(
	Fyuu_Platform* platform,
	void* user_data
) NOEXCEPT;

/* Called once per Fyuu_RuntimeTick to pump events and report an OS close request. */
typedef Fyuu_Result (LIB_CALL* Fyuu_PlatformPumpEventsCallback)(
	Fyuu_Platform* platform,
	void* user_data,
	bool* close_requested
) NOEXCEPT;

/* Called by Fyuu_PlatformDestroy when platform initialization completed. */
typedef void (LIB_CALL* Fyuu_PlatformShutdownCallback)(
	Fyuu_Platform* platform,
	void* user_data
) NOEXCEPT;

/* Describes a borrowed platform implementation and its lifecycle callbacks. */
typedef struct Fyuu_PlatformDescriptor {{
	size_t struct_size;
	uint32_t ABI_version;
	void* user_data;
	Fyuu_PlatformInitializeCallback {callbacks['initialize']['c_name']};
	Fyuu_PlatformPumpEventsCallback {callbacks['pump_events']['c_name']};
	Fyuu_PlatformShutdownCallback {callbacks['shutdown']['c_name']};
}} Fyuu_PlatformDescriptor;

/* Allocates an opaque platform object and copies descriptor; callbacks are not invoked yet. */
LIB_API Fyuu_Result LIB_CALL Fyuu_PlatformCreate(
	Fyuu_PlatformDescriptor const* descriptor,
	Fyuu_Platform** output
) NOEXCEPT;

/* Invokes shutdown when needed and releases the opaque platform object. */
LIB_API void LIB_CALL Fyuu_PlatformDestroy(
	Fyuu_Platform* platform
) NOEXCEPT;

#if defined(__cplusplus)
}}
#endif
"""


def render_runtime(schema):
	callbacks = schema["application_callbacks"]
	require_keys(callbacks, ("initialize", "tick", "close_requested", "shutdown"), "application_callbacks")
	state_items = ",\n".join(
		f"\t{item['c_name']} = {item['value']}"
		for item in schema["runtime_states"].values()
	)
	return f"""{GENERATED}
#pragma once

#include <stddef.h>
#include <stdint.h>

#include "api_macro.h"
#include "fyuu_log.h"
#include "fyuu_platform.h"

#if defined(__cplusplus)
extern "C" {{
#endif

/*
 * Native call chain:
 * fyuu_engine::Runtime -> C ABI entry -> runtime state machine -> callback -> generated thunk -> Application.
 * C callers enter at the C ABI entry and provide callbacks directly.
 */
typedef struct Fyuu_Runtime Fyuu_Runtime;

/* Application lifecycle callback used for initialize, tick, and shutdown. */
typedef void (LIB_CALL* Fyuu_RuntimeCallback)(
	Fyuu_Runtime* runtime,
	void* user_data
) NOEXCEPT;

/* Decides whether a close request reported by the platform may stop the runtime. */
typedef bool (LIB_CALL* Fyuu_RuntimeCloseRequestedCallback)(
	Fyuu_Runtime* runtime,
	void* user_data
) NOEXCEPT;

/* Describes a borrowed application implementation and its lifecycle callbacks. */
typedef struct Fyuu_RuntimeDescriptor {{
	size_t struct_size;
	uint32_t ABI_version;
	void* user_data;
	/* Optional borrowed logger used by the shared Runtime state machine; must remain alive. */
	Fyuu_Logger* logger;
	Fyuu_RuntimeCallback {callbacks['initialize']['c_name']};
	Fyuu_RuntimeCallback {callbacks['tick']['c_name']};
	Fyuu_RuntimeCloseRequestedCallback {callbacks['close_requested']['c_name']};
	Fyuu_RuntimeCallback {callbacks['shutdown']['c_name']};
}} Fyuu_RuntimeDescriptor;

/* State is owned by the C ABI core and observed by both C and module callers. */
typedef enum Fyuu_RuntimeState {{
{state_items}
}} Fyuu_RuntimeState;

/* Allocates a runtime that borrows platform and copies descriptor. */
LIB_API Fyuu_Result LIB_CALL Fyuu_RuntimeCreate(
	Fyuu_Platform* platform,
	Fyuu_RuntimeDescriptor const* descriptor,
	Fyuu_Runtime** output
) NOEXCEPT;

/* Initializes platform, calls application initialize, and enters Running. */
LIB_API Fyuu_Result LIB_CALL Fyuu_RuntimeInitialize(
	Fyuu_Runtime* runtime
) NOEXCEPT;

/* Pumps events, negotiates closure, calls application tick, and completes stopping. */
LIB_API Fyuu_Result LIB_CALL Fyuu_RuntimeTick(
	Fyuu_Runtime* runtime
) NOEXCEPT;

/* Changes Running to StopRequested; shutdown completes on the next tick or destroy. */
LIB_API void LIB_CALL Fyuu_RuntimeRequestStop(
	Fyuu_Runtime* runtime
) NOEXCEPT;

/* Returns Stopped for a null pointer; otherwise returns the current core state. */
LIB_API Fyuu_RuntimeState LIB_CALL Fyuu_RuntimeGetState(
	Fyuu_Runtime const* runtime
) NOEXCEPT;

/* Completes application shutdown when needed and releases the opaque runtime. */
LIB_API void LIB_CALL Fyuu_RuntimeDestroy(
	Fyuu_Runtime* runtime
) NOEXCEPT;

#if defined(__cplusplus)
}}
#endif
"""


def render_log(schema):
	level_items = ",\n".join(
		f"\t{item['c_name']} = {item['value']}"
		for item in schema["log_levels"].values()
	)
	return f"""{GENERATED}
#pragma once

#include <stddef.h>
#include <stdint.h>

#include "api_macro.h"
#include "fyuu_result.h"

#if defined(__cplusplus)
extern "C" {{
#endif

typedef struct Fyuu_Logger Fyuu_Logger;

typedef enum Fyuu_LogLevel {{
{level_items}
}} Fyuu_LogLevel;

/* Borrowed string data remains valid only for the duration of the sink callback. */
typedef struct Fyuu_LogRecord {{
	Fyuu_LogLevel level;
	char const* category_data;
	size_t category_size;
	char const* message_data;
	size_t message_size;
}} Fyuu_LogRecord;

typedef Fyuu_Result (LIB_CALL* Fyuu_LogSinkCallback)(
	Fyuu_Logger* logger,
	void* user_data,
	Fyuu_LogRecord const* record
) NOEXCEPT;

typedef struct Fyuu_LoggerDescriptor {{
	size_t struct_size;
	uint32_t ABI_version;
	void* user_data;
	Fyuu_LogSinkCallback sink;
}} Fyuu_LoggerDescriptor;

/* Allocates a logger and copies descriptor without taking ownership of user_data. */
LIB_API Fyuu_Result LIB_CALL Fyuu_LoggerCreate(
	Fyuu_LoggerDescriptor const* descriptor,
	Fyuu_Logger** output
) NOEXCEPT;

/* Sends one borrowed record to the configured sink synchronously. */
LIB_API Fyuu_Result LIB_CALL Fyuu_LoggerWrite(
	Fyuu_Logger* logger,
	Fyuu_LogRecord const* record
) NOEXCEPT;

/* Releases the logger without destroying the borrowed sink. */
LIB_API void LIB_CALL Fyuu_LoggerDestroy(
	Fyuu_Logger* logger
) NOEXCEPT;

#if defined(__cplusplus)
}}
#endif
"""


def enum_body(mapping):
	return ",\n".join(
		f"\t\t{name} = {item['c_name']}"
		for name, item in mapping.items()
	)


def render_types_module(schema):
	results = enum_body(schema["results"])
	states = enum_body(schema["runtime_states"])
	levels = enum_body(schema["log_levels"])
	module = schema["module"]
	namespace = schema["namespace"]
	return f"""{GENERATED}
module;
#include "fyuu_result.h"
#include "fyuu_log.h"
#include "fyuu_runtime.h"

export module {module}:api_types;

export namespace {namespace} {{

	/// Type-safe mapping of Fyuu_Result. Values remain identical across both entry surfaces.
	enum class Result {{
{results}
	}};

	/// Type-safe mapping of Fyuu_RuntimeState owned by the shared C ABI state machine.
	enum class RuntimeState {{
{states}
	}};

	/// Severity carried unchanged by the C ABI and native logging entry points.
	enum class LogLevel {{
{levels}
	}};

}}
"""


def render_glue(schema):
	platform = schema["platform_callbacks"]
	application = schema["application_callbacks"]
	module = schema["module"]
	return f"""{GENERATED}
module;
#include <version>
#if !defined(__cpp_lib_modules)
#include <exception>
#include <string_view>
#endif // !defined(__cpp_lib_modules)
#include "fyuu_log.h"
#include "fyuu_platform.h"
#include "fyuu_runtime.h"

module {module}:api_glue;

import {module};
#if defined(__cpp_lib_modules)
import std;
#endif // defined(__cpp_lib_modules)

namespace {schema["namespace"]} {{

	// C ABI callback -> this thunk -> LogSink::Write.
	Fyuu_Result LIB_CALL Logger::WriteThunk(
		Fyuu_Logger*,
		void* user_data,
		Fyuu_LogRecord const* record
	) noexcept {{
		auto* self = static_cast<Logger*>(user_data);
		LogRecord const native_record{{
			static_cast<LogLevel>(record->level),
			std::string_view{{ record->category_data ? record->category_data : "", record->category_size }},
			std::string_view{{ record->message_data ? record->message_data : "", record->message_size }}
		}};
		try {{
			self->m_sink->Write(native_record);
			return FYUU_RESULT_SUCCESS;
		}}
		catch (...) {{
			self->m_pending_exception = std::current_exception();
			return FYUU_RESULT_LOG_ERROR;
		}}
	}}

	// C ABI callback -> this thunk -> Platform::{platform["pump_events"]["cpp_name"]}.
	Fyuu_Result LIB_CALL Platform::PumpEventsThunk(
		Fyuu_Platform*,
		void* user_data,
		bool* close_requested
	) noexcept {{
		auto* self = static_cast<Platform*>(user_data);
		try {{
			self->{platform["pump_events"]["cpp_name"]}(*close_requested);
			return FYUU_RESULT_SUCCESS;
		}}
		catch (...) {{
			self->m_pending_exception = std::current_exception();
			return FYUU_RESULT_PLATFORM_ERROR;
		}}
	}}

	// C ABI callback -> this thunk -> Application::{application["tick"]["cpp_name"]}.
	void LIB_CALL Runtime::TickThunk(
		Fyuu_Runtime*,
		void* user_data
	) noexcept {{
		auto* self = static_cast<Runtime*>(user_data);
		try {{
			self->m_application->{application["tick"]["cpp_name"]}(*self);
		}}
		catch (...) {{
			self->m_pending_exception = std::current_exception();
		}}
	}}

	// C ABI callback -> this thunk -> Application::{application["close_requested"]["cpp_name"]}.
	bool LIB_CALL Runtime::CloseRequestedThunk(
		Fyuu_Runtime*,
		void* user_data
	) noexcept {{
		auto* self = static_cast<Runtime*>(user_data);
		try {{
			return self->m_application->{application["close_requested"]["cpp_name"]}(*self);
		}}
		catch (...) {{
			self->m_pending_exception = std::current_exception();
			return true;
		}}
	}}

}}
"""


def outputs(root, schema):
	return {
		root / "include" / "fyuu_types.h": render_types(schema),
		root / "include" / "fyuu_result.h": render_result(schema),
		root / "include" / "fyuu_platform.h": render_platform(schema),
		root / "include" / "fyuu_log.h": render_log(schema),
		root / "include" / "fyuu_runtime.h": render_runtime(schema),
		root / "runtime" / "module" / "generated" / "api_types.cppm": render_types_module(schema),
		root / "runtime" / "module" / "internal" / "generated" / "api_glue.cpp": render_glue(schema),
	}


def main():
	parser = argparse.ArgumentParser(
		description="Generate the Fyuu Runtime C ABI and C++ module glue from YAML.",
		epilog=HELP,
		formatter_class=argparse.RawDescriptionHelpFormatter
	)
	parser.add_argument(
		"--check",
		action="store_true",
		help="check whether generated files are current without writing them"
	)
	parser.add_argument(
		"--schema",
		type=Path,
		metavar="PATH",
		help="use PATH instead of conf/runtime_api.yaml"
	)
	arguments = parser.parse_args()
	root = Path(__file__).resolve().parents[1]
	schema_path = arguments.schema or root / "conf" / "runtime_api.yaml"
	try:
		schema = load_yaml(schema_path)
		require_keys(
			schema,
			(
				"abi_version", "module", "namespace", "results", "runtime_states", "log_levels",
				"platform_callbacks",
				"application_callbacks"
			),
			str(schema_path)
		)
	except (OSError, ValueError) as error:
		print(error, file=sys.stderr)
		return 2
	stale = []
	for path, content in outputs(root, schema).items():
		content = content.replace("\r\n", "\n")
		if arguments.check:
			current = path.read_text(encoding="utf-8") if path.exists() else ""
			if current.replace("\r\n", "\n") != content:
				stale.append(path)
			continue
		path.parent.mkdir(parents=True, exist_ok=True)
		path.write_text(content, encoding="utf-8", newline="\n")
		print(path.relative_to(root))
	if stale:
		for path in stale:
			print(f"stale: {path.relative_to(root)}", file=sys.stderr)
		return 1
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
