// Generated by script/generate_runtime_api.py. Do not edit.
#pragma once

#include <stddef.h>
#include <stdint.h>

#include "api_macro.h"
#include "fyuu_result.h"

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * Native call chain:
 * fyuu_engine::Platform -> C ABI entry -> platform state -> callback -> generated thunk -> Platform.
 * C callers enter at the C ABI entry and provide callbacks directly.
 */
typedef struct Fyuu_Platform Fyuu_Platform;

/* Called by Fyuu_RuntimeInitialize before the application initialize callback. */
typedef Fyuu_Result (LIB_CALL* Fyuu_PlatformInitializeCallback)(
	Fyuu_Platform* platform,
	void* user_data
) NOEXCEPT;

/* Called once per Fyuu_RuntimeTick to pump events and report an OS close request. */
typedef Fyuu_Result (LIB_CALL* Fyuu_PlatformPumpEventsCallback)(
	Fyuu_Platform* platform,
	void* user_data,
	bool* close_requested
) NOEXCEPT;

/* Called by Fyuu_PlatformDestroy when platform initialization completed. */
typedef void (LIB_CALL* Fyuu_PlatformShutdownCallback)(
	Fyuu_Platform* platform,
	void* user_data
) NOEXCEPT;

/* Describes a borrowed platform implementation and its lifecycle callbacks. */
typedef struct Fyuu_PlatformDescriptor {
	size_t struct_size;
	uint32_t ABI_version;
	void* user_data;
	Fyuu_PlatformInitializeCallback initialize;
	Fyuu_PlatformPumpEventsCallback pump_events;
	Fyuu_PlatformShutdownCallback shutdown;
} Fyuu_PlatformDescriptor;

/* Allocates an opaque platform object and copies descriptor; callbacks are not invoked yet. */
LIB_API Fyuu_Result LIB_CALL Fyuu_PlatformCreate(
	Fyuu_PlatformDescriptor const* descriptor,
	Fyuu_Platform** output
) NOEXCEPT;

/* Invokes shutdown when needed and releases the opaque platform object. */
LIB_API void LIB_CALL Fyuu_PlatformDestroy(
	Fyuu_Platform* platform
) NOEXCEPT;

#if defined(__cplusplus)
}
#endif
