// Generated by script/generate_runtime_api.py. Do not edit.
#pragma once

#include <stddef.h>
#include <stdint.h>

#include "api_macro.h"
#include "fyuu_log.h"
#include "fyuu_platform.h"

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * Native call chain:
 * fyuu_engine::Runtime -> C ABI entry -> runtime state machine -> callback -> generated thunk -> Application.
 * C callers enter at the C ABI entry and provide callbacks directly.
 */
typedef struct Fyuu_Runtime Fyuu_Runtime;

/* Application lifecycle callback used for initialize, tick, and shutdown. */
typedef void (LIB_CALL* Fyuu_RuntimeCallback)(
	Fyuu_Runtime* runtime,
	void* user_data
) NOEXCEPT;

/* Decides whether a close request reported by the platform may stop the runtime. */
typedef bool (LIB_CALL* Fyuu_RuntimeCloseRequestedCallback)(
	Fyuu_Runtime* runtime,
	void* user_data
) NOEXCEPT;

/* Describes a borrowed application implementation and its lifecycle callbacks. */
typedef struct Fyuu_RuntimeDescriptor {
	size_t struct_size;
	uint32_t ABI_version;
	void* user_data;
	/* Optional borrowed logger used by the shared Runtime state machine; must remain alive. */
	Fyuu_Logger* logger;
	Fyuu_RuntimeCallback initialize;
	Fyuu_RuntimeCallback tick;
	Fyuu_RuntimeCloseRequestedCallback close_requested;
	Fyuu_RuntimeCallback shutdown;
} Fyuu_RuntimeDescriptor;

/* State is owned by the C ABI core and observed by both C and module callers. */
typedef enum Fyuu_RuntimeState {
	FYUU_RUNTIME_STATE_CREATED = 0,
	FYUU_RUNTIME_STATE_RUNNING = 1,
	FYUU_RUNTIME_STATE_STOP_REQUESTED = 2,
	FYUU_RUNTIME_STATE_STOPPED = 3
} Fyuu_RuntimeState;

/* Allocates a runtime that borrows platform and copies descriptor. */
LIB_API Fyuu_Result LIB_CALL Fyuu_RuntimeCreate(
	Fyuu_Platform* platform,
	Fyuu_RuntimeDescriptor const* descriptor,
	Fyuu_Runtime** output
) NOEXCEPT;

/* Initializes platform, calls application initialize, and enters Running. */
LIB_API Fyuu_Result LIB_CALL Fyuu_RuntimeInitialize(
	Fyuu_Runtime* runtime
) NOEXCEPT;

/* Pumps events, negotiates closure, calls application tick, and completes stopping. */
LIB_API Fyuu_Result LIB_CALL Fyuu_RuntimeTick(
	Fyuu_Runtime* runtime
) NOEXCEPT;

/* Changes Running to StopRequested; shutdown completes on the next tick or destroy. */
LIB_API void LIB_CALL Fyuu_RuntimeRequestStop(
	Fyuu_Runtime* runtime
) NOEXCEPT;

/* Returns Stopped for a null pointer; otherwise returns the current core state. */
LIB_API Fyuu_RuntimeState LIB_CALL Fyuu_RuntimeGetState(
	Fyuu_Runtime const* runtime
) NOEXCEPT;

/* Completes application shutdown when needed and releases the opaque runtime. */
LIB_API void LIB_CALL Fyuu_RuntimeDestroy(
	Fyuu_Runtime* runtime
) NOEXCEPT;

#if defined(__cplusplus)
}
#endif
