// Generated by script/generate_runtime_api.py. Do not edit.
#pragma once

#include <stdbool.h>
#include <stdint.h>

/* Version carried by every extensible descriptor passed across the C ABI. */
#define FYUU_ABI_VERSION ((uint32_t)1u)
