// Generated by script/generate_runtime_api.py. Do not edit.
#pragma once

#include <stddef.h>
#include <stdint.h>

#include "api_macro.h"
#include "fyuu_result.h"

#if defined(__cplusplus)
extern "C" {
#endif

typedef struct Fyuu_Logger Fyuu_Logger;

typedef enum Fyuu_LogLevel {
	FYUU_LOG_LEVEL_TRACE = 0,
	FYUU_LOG_LEVEL_DEBUG = 1,
	FYUU_LOG_LEVEL_INFO = 2,
	FYUU_LOG_LEVEL_WARNING = 3,
	FYUU_LOG_LEVEL_ERROR = 4,
	FYUU_LOG_LEVEL_FATAL = 5
} Fyuu_LogLevel;

/* Borrowed string data remains valid only for the duration of the sink callback. */
typedef struct Fyuu_LogRecord {
	Fyuu_LogLevel level;
	char const* category_data;
	size_t category_size;
	char const* message_data;
	size_t message_size;
} Fyuu_LogRecord;

typedef Fyuu_Result (LIB_CALL* Fyuu_LogSinkCallback)(
	Fyuu_Logger* logger,
	void* user_data,
	Fyuu_LogRecord const* record
) NOEXCEPT;

typedef struct Fyuu_LoggerDescriptor {
	size_t struct_size;
	uint32_t ABI_version;
	void* user_data;
	Fyuu_LogSinkCallback sink;
} Fyuu_LoggerDescriptor;

/* Allocates a logger and copies descriptor without taking ownership of user_data. */
LIB_API Fyuu_Result LIB_CALL Fyuu_LoggerCreate(
	Fyuu_LoggerDescriptor const* descriptor,
	Fyuu_Logger** output
) NOEXCEPT;

/* Sends one borrowed record to the configured sink synchronously. */
LIB_API Fyuu_Result LIB_CALL Fyuu_LoggerWrite(
	Fyuu_Logger* logger,
	Fyuu_LogRecord const* record
) NOEXCEPT;

/* Releases the logger without destroying the borrowed sink. */
LIB_API void LIB_CALL Fyuu_LoggerDestroy(
	Fyuu_Logger* logger
) NOEXCEPT;

#if defined(__cplusplus)
}
#endif
